### ISSUE TITLE
kid can only take 2 candies, not 5

### ISSUE THREAD

**Issue by LaFesta1749** [Waltuhs/InterestingSubClasses#1]
@Waltuhs I was a **kid** role and I got 3 candies and my hands dropped on the table (broadcast says the "kid" can take up to 5 candies)... Then I died :(

Video: https://medal.tv/games/scp-secret-laboratory/clips/i3vZknerX8py4M6aJ/d1337ZKaoTmB?invite=cr-MSxjWG0sMjI3ODA2MjQzLA

![image](https://github.com/Waltuhs/InterestingSubClasses/assets/1494298/eae12c41-b7dc-4cd9-8ceb-39ceb61e275b)

**Comment by Waltuhs** [comment]
@LaFesta1749 This feature is not able to work with CandyUtils Because for whatever reason they Patch it for ALL PEOPLE in the server to only be able to pickup whatever the max count is. there is nothing i can do about this but advise you to turn off candy utils or the kid role or change the translation
